INSERT INTO [dbo].[PersonnageLangue] ([LangueId], [PersonnageId]) VALUES (1, 1)
INSERT INTO [dbo].[PersonnageLangue] ([LangueId], [PersonnageId]) VALUES (9, 1)
INSERT INTO [dbo].[PersonnageLangue] ([LangueId], [PersonnageId]) VALUES (12, 1)

INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (1, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (2, 1, 1, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (3, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (4, 1, 1, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (5, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (6, 1, 0, 1)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (7, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (8, 1, 0, 1)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (9, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (10, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (11, 1, 1, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (12, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (13, 1, 0, 1)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (14, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (15, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (16, 1, 0, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (17, 1, 1, 0)
INSERT INTO [dbo].[PersonnageCompetence] ([CompetenceId], [PersonnageId], [Maitrise], [Expertise]) VALUES (18, 1, 0, 0)


INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (1, 1, 15, NULL)
INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (2, 1, 10, NULL)
INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (3, 1, 11, NULL)
INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (4, 1, 13, NULL)
INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (5, 1, 14, NULL)
INSERT INTO [dbo].[PersonnageCaracteristique] ([CaracteristiqueId], [PersonnageId], [Valeur], [ValeurTemporaire]) VALUES (6, 1, 12, NULL)
